// Textes traduits du site.
// Le français est directement dans le HTML : ici on ne met que l'anglais et l'indonésien.
// Chaque clé correspond à un attribut data-i18n="cle" (texte) ou data-i18n-attr="attribut:cle" dans le HTML.

const traductions = {
  // Textes utilisés uniquement par le JavaScript
  fr: {
    "burger.ouvrir": "Ouvrir le menu",
    "burger.fermer": "Fermer le menu",
  },

  en: {
    // Commun
    "nav.label": "Main navigation",
    "nav.projets": "Projects",
    "nav.apropos": "About",
    "nav.contact": "Contact",
    "burger.ouvrir": "Open menu",
    "burger.fermer": "Close menu",
    "theme.sombre": "Dark mode",
    "theme.clair": "Light mode",
    "langues.label": "Language",
    "footer.email": "Send me a message",
    "photo.alt": "Photo of Alison Faidherbe",
    "projets.titre": "My projects",
    "projets.voirTous": "See all my projects",

    // Accueil
    "index.titre": "Alison Faidherbe · Fullstack web developer",
    "index.description": "Portfolio of Alison Faidherbe, junior fullstack web developer.",
    "accueil.h1": "<strong>Fullstack</strong><br> web <strong>developer</strong>",
    "accueil.accroche": "Any questions?",
    "accueil.contact": "Contact me",
    "competences.titre": "Skills",
    "competences.bdd": "Databases",

    // Projets
    "projets.pageTitre": "Projects · Alison Faidherbe",
    "projets.description": "Web projects by Alison Faidherbe.",
    "projet.groupe": "Group project",
    "projet.perso": "Personal project",
    "projet.enCours": "Work in progress",
    "projet.voir": "View the project",
    "projet.visualiser": "Click here to view the project",
    "cabron.logo": "I lost my Cabron logo",
    "cabron.galerie": "Screenshots of I lost my Cabron",
    "cabron.accueil": "I lost my Cabron home page",
    "cabron.connexion": "I lost my Cabron login page",
    "cabron.annonces": "List of lost and found animals on I lost my Cabron",
    "marie.accueil": "Aux créas de Marie home page",
    "marie.catalogue": "Aux créas de Marie product catalogue",
    "floppy.capture": "Floppy Perroquet game start screen",
    "projet.jouer": "Click here to play",
    "marie.galerie": "Screenshots of Aux créas de Marie",
    "galerie.precedent": "Previous screenshot",
    "galerie.suivant": "Next screenshot",
    "ecf.capture": "Screenshot of the ECF project: the Ma Bibliothèque app",

    // Contact
    "contact.pageTitre": "Contact · Alison Faidherbe",
    "contact.description": "Contact Alison Faidherbe, fullstack web developer.",
    "form.nom": "Last name",
    "form.prenom": "First name",
    "form.email": "Email",
    "form.message": "Message",
    "form.envoyer": "Send",

    // À propos
    "apropos.pageTitre": "About · Alison Faidherbe",
    "apropos.description": "Background, education and skills of Alison Faidherbe.",
    "apropos.h1": "About me",
    "formations.titre": "Education &amp; qualifications",
    "formation.2026": "<time>2026</time> - Professional qualification, level 5 - <strong>Web and mobile web developer</strong> (in progress, ends November 2026).",
    "formation.2025": "<time>2025</time> - First aid training, level 1 (PSC1).",
    "formation.2020": "<time>2020</time> - Advanced technical qualification certificate: qualified to lead a team of 9 people.",
    "formation.2015": "<time>2015</time> - <strong>ST2S Baccalaureate</strong> - Health and Social Sciences and Technologies.",
    "experiences.titre": "Work experience",
    "exp1.titre": "Dog handler",
    "exp1.lieu": "Ministry of the Armed Forces - French Army",
    "exp2.titre": "Reserve assistant gendarme",
    "exp2.lieu": "French Gendarmerie",
    "exp1.mission": "Training and care of operational dogs.",
    "exp2.mission": "Security and prevention missions in the field.",
    "profil.label": "Profile",
    "atouts.titre": "Strengths",
    "atouts.autonome": "Independent",
    "atouts.equipe": "Teamwork",
    "atouts.rigoureuse": "Rigorous",
    "atouts.curieuse": "Curious",
    "divers.titre": "Languages &amp; licences",
    "divers.anglais": "English B2",
    "divers.permis": "Driving licence: car and truck",
    "competences.technique": "Technical skills",
    "histoire.titre": "My story",
    "histoire.p1": "Training a dog and writing code take the same things: patience, method and plenty of perseverance. I learned this over 11 years as a military dog handler in the French Army, where I also learned to lead a team.",
    "histoire.p2": "Now training as a fullstack web developer, I bring these same qualities to building websites and applications.",
    "histoire.p3": "I'm open to new opportunities.",
    "cv": "Download my CV",
    "cv.lien": "assets/CV_Alison_Faidherbe_web_en.pdf?v=2026-09-25-4",
    "interets.titre": "Interests",
    "interets.course": "Running",
    "interets.velo": "Road cycling",
    "interets.snowboard": "Snowboarding",
    "interets.voyages": "Travelling",
  },

  id: {
    // Commun
    "nav.label": "Navigasi utama",
    "nav.projets": "Proyek",
    "nav.apropos": "Tentang saya",
    "nav.contact": "Kontak",
    "burger.ouvrir": "Buka menu",
    "burger.fermer": "Tutup menu",
    "theme.sombre": "Mode gelap",
    "theme.clair": "Mode terang",
    "langues.label": "Bahasa",
    "footer.email": "Kirimi saya pesan",
    "photo.alt": "Foto Alison Faidherbe",
    "projets.titre": "Proyek saya",
    "projets.voirTous": "Lihat semua proyek saya",

    // Accueil
    "index.titre": "Alison Faidherbe · Pengembang web fullstack",
    "index.description": "Portofolio Alison Faidherbe, pengembang web fullstack junior.",
    "accueil.h1": "<strong>Pengembang</strong><br> Web <strong>fullstack</strong>",
    "accueil.accroche": "Ada pertanyaan?",
    "accueil.contact": "Hubungi saya",
    "competences.titre": "Keahlian",
    "competences.bdd": "Basis data",

    // Projets
    "projets.pageTitre": "Proyek · Alison Faidherbe",
    "projets.description": "Proyek web karya Alison Faidherbe.",
    "projet.groupe": "Proyek kelompok",
    "projet.perso": "Proyek pribadi",
    "projet.enCours": "Sedang dikerjakan",
    "projet.voir": "Lihat proyek",
    "projet.visualiser": "Klik di sini untuk melihat proyek",
    "cabron.logo": "Logo I lost my Cabron",
    "cabron.galerie": "Tangkapan layar I lost my Cabron",
    "cabron.accueil": "Halaman beranda I lost my Cabron",
    "cabron.connexion": "Halaman masuk I lost my Cabron",
    "cabron.annonces": "Daftar hewan hilang dan ditemukan di I lost my Cabron",
    "marie.accueil": "Halaman beranda Aux créas de Marie",
    "marie.catalogue": "Katalog kreasi Aux créas de Marie",
    "floppy.capture": "Layar awal gim Floppy Perroquet",
    "projet.jouer": "Klik di sini untuk bermain",
    "marie.galerie": "Tangkapan layar Aux créas de Marie",
    "galerie.precedent": "Tangkapan layar sebelumnya",
    "galerie.suivant": "Tangkapan layar berikutnya",
    "ecf.capture": "Tangkapan layar proyek ECF: aplikasi Ma Bibliothèque",

    // Contact
    "contact.pageTitre": "Kontak · Alison Faidherbe",
    "contact.description": "Hubungi Alison Faidherbe, pengembang web fullstack.",
    "form.nom": "Nama belakang",
    "form.prenom": "Nama depan",
    "form.email": "Email",
    "form.message": "Pesan",
    "form.envoyer": "Kirim",

    // À propos
    "apropos.pageTitre": "Tentang saya · Alison Faidherbe",
    "apropos.description": "Latar belakang, pendidikan, dan keahlian Alison Faidherbe.",
    "apropos.h1": "Tentang saya",
    "formations.titre": "Pendidikan &amp; sertifikat",
    "formation.2026": "<time>2026</time> - Sertifikat profesi level 5 - <strong>Pengembang web dan web mobile</strong> (sedang berjalan, selesai November 2026).",
    "formation.2025": "<time>2025</time> - Pelatihan pertolongan pertama tingkat 1 (PSC1).",
    "formation.2020": "<time>2020</time> - Sertifikat kualifikasi teknis lanjutan: mampu memimpin tim beranggotakan 9 orang.",
    "formation.2015": "<time>2015</time> - <strong>Baccalauréat ST2S</strong> - Ilmu dan teknologi kesehatan dan sosial.",
    "experiences.titre": "Pengalaman kerja",
    "exp1.titre": "Pawang anjing",
    "exp1.lieu": "Kementerian Angkatan Bersenjata - Angkatan Darat Prancis",
    "exp2.titre": "Gendarme cadangan",
    "exp2.lieu": "Gendarmerie Prancis",
    "exp1.mission": "Melatih dan merawat anjing operasional.",
    "exp2.mission": "Misi keamanan dan pencegahan di lapangan.",
    "profil.label": "Profil",
    "atouts.titre": "Kelebihan",
    "atouts.autonome": "Mandiri",
    "atouts.equipe": "Kerja tim",
    "atouts.rigoureuse": "Teliti",
    "atouts.curieuse": "Ingin tahu",
    "divers.titre": "Bahasa &amp; SIM",
    "divers.anglais": "Bahasa Inggris B2",
    "divers.permis": "SIM Prancis: mobil dan truk",
    "competences.technique": "Keahlian teknis",
    "histoire.titre": "Cerita saya",
    "histoire.p1": "Melatih anjing dan menulis kode membutuhkan hal yang sama: kesabaran, metode, dan ketekunan. Saya mengalaminya selama 11 tahun sebagai pawang anjing di Angkatan Darat Prancis, dimana saya juga belajar memimpin tim.",
    "histoire.p2": "Kini sedang menempuh pelatihan pengembang web fullstack, saya menerapkan kualitas yang sama dalam membangun situs dan aplikasi.",
    "histoire.p3": "Saya terbuka untuk peluang baru.",
    "cv": "Unduh CV saya",
    "cv.lien": "assets/CV_Alison_Faidherbe_web_id.pdf?v=2026-09-25-4",
    "interets.titre": "Minat",
    "interets.course": "Lari",
    "interets.velo": "Bersepeda jalan raya",
    "interets.snowboard": "Snowboard",
    "interets.voyages": "Jalan-jalan",
  },
};
